# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  stripe_publishable_key: pk_test_LTnMfF09mQqrXZIwJ4D19Qd7
  stripe_secret_key: sk_test_PVuhWdovATDkYunzGcYxbyvl
  secret_key_base: 1f1523b4ce098c23713a9c2d350f97ddcbd18593446d2486524ed12ef0cbb42ea3ebae8927c734c98ebfd8b0d3a95034391101e59f4a8ece1e97096f24c9fd1a

test:
  secret_key_base: e4d090a23ac01ec418111a44c7b1430a3cd828eb62e0b45d5a9f2cb1c4faa3d4de792a474622958c2f88a6745723a6c392e6d995d939e76b87be754f9d25536c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
